// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2nTFNrNaiDiRTaTQGHrWQ77zN6vFWTy8',
    appId: '1:522601583189:web:a80c57ca9939fe17e67adc',
    messagingSenderId: '522601583189',
    projectId: 'gym-backend-d576c',
    authDomain: 'gym-backend-d576c.firebaseapp.com',
    storageBucket: 'gym-backend-d576c.firebasestorage.app',
    measurementId: 'G-RJL37GV8QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOLAv0ddVDw_jOVK_61PGYzVziUiiDIw',
    appId: '1:522601583189:android:781d8306ab2aad9de67adc',
    messagingSenderId: '522601583189',
    projectId: 'gym-backend-d576c',
    storageBucket: 'gym-backend-d576c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDAmoVzVDnpeulKTDRgXou_pG8qjZ7RI',
    appId: '1:522601583189:ios:527fb9f5af8706e4e67adc',
    messagingSenderId: '522601583189',
    projectId: 'gym-backend-d576c',
    storageBucket: 'gym-backend-d576c.firebasestorage.app',
    iosBundleId: 'com.example.gym1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxDAmoVzVDnpeulKTDRgXou_pG8qjZ7RI',
    appId: '1:522601583189:ios:527fb9f5af8706e4e67adc',
    messagingSenderId: '522601583189',
    projectId: 'gym-backend-d576c',
    storageBucket: 'gym-backend-d576c.firebasestorage.app',
    iosBundleId: 'com.example.gym1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2nTFNrNaiDiRTaTQGHrWQ77zN6vFWTy8',
    appId: '1:522601583189:web:c2199988b40e6141e67adc',
    messagingSenderId: '522601583189',
    projectId: 'gym-backend-d576c',
    authDomain: 'gym-backend-d576c.firebaseapp.com',
    storageBucket: 'gym-backend-d576c.firebasestorage.app',
    measurementId: 'G-8HPS9V7N7Q',
  );
}
